/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109078-g2d25f33a7e-20221113"
#endif /* AVUTIL_FFVERSION_H */
